package com.dag.robot.entities;

// Generated 2015-5-18 21:02:56 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelExpertPatentId generated by hbm2java
 */
@Embeddable
public class RelExpertPatentId implements java.io.Serializable {

	private int expertId;
	private int patentId;

	public RelExpertPatentId() {
	}

	public RelExpertPatentId(int expertId, int patentId) {
		this.expertId = expertId;
		this.patentId = patentId;
	}

	@Column(name = "expertId", nullable = false)
	public int getExpertId() {
		return this.expertId;
	}

	public void setExpertId(int expertId) {
		this.expertId = expertId;
	}

	@Column(name = "patentId", nullable = false)
	public int getPatentId() {
		return this.patentId;
	}

	public void setPatentId(int patentId) {
		this.patentId = patentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelExpertPatentId))
			return false;
		RelExpertPatentId castOther = (RelExpertPatentId) other;

		return (this.getExpertId() == castOther.getExpertId())
				&& (this.getPatentId() == castOther.getPatentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getExpertId();
		result = 37 * result + this.getPatentId();
		return result;
	}

}
