package com.dag.robot.entities;

// Generated 2015-5-13 19:55:40 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelExpertTopic generated by hbm2java
 */
@Entity
@Table(name = "rel_expert_topic", catalog = "db_expert_robot")
public class RelExpertTopic implements java.io.Serializable {

	private RelExpertTopicId id;
	private Expert expert;
	private Topic topic;
	private Integer weight;

	public RelExpertTopic() {
	}

	public RelExpertTopic(RelExpertTopicId id, Expert expert, Topic topic) {
		this.id = id;
		this.expert = expert;
		this.topic = topic;
	}

	public RelExpertTopic(RelExpertTopicId id, Expert expert, Topic topic,
			Integer weight) {
		this.id = id;
		this.expert = expert;
		this.topic = topic;
		this.weight = weight;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "expertId", column = @Column(name = "expertId", nullable = false)),
			@AttributeOverride(name = "topicId", column = @Column(name = "topicId", nullable = false)) })
	public RelExpertTopicId getId() {
		return this.id;
	}

	public void setId(RelExpertTopicId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expertId", nullable = false, insertable = false, updatable = false)
	public Expert getExpert() {
		return this.expert;
	}

	public void setExpert(Expert expert) {
		this.expert = expert;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "topicId", nullable = false, insertable = false, updatable = false)
	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	@Column(name = "weight")
	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

}
