package com.dag.robot.entities;

// Generated 2015-5-19 21:06:32 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelExpertTopicId generated by hbm2java
 */
@Embeddable
public class RelExpertTopicId implements java.io.Serializable {

	private int expertId;
	private int topicId;

	public RelExpertTopicId() {
	}

	public RelExpertTopicId(int expertId, int topicId) {
		this.expertId = expertId;
		this.topicId = topicId;
	}

	@Column(name = "expertId", nullable = false)
	public int getExpertId() {
		return this.expertId;
	}

	public void setExpertId(int expertId) {
		this.expertId = expertId;
	}

	@Column(name = "topicId", nullable = false)
	public int getTopicId() {
		return this.topicId;
	}

	public void setTopicId(int topicId) {
		this.topicId = topicId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelExpertTopicId))
			return false;
		RelExpertTopicId castOther = (RelExpertTopicId) other;

		return (this.getExpertId() == castOther.getExpertId())
				&& (this.getTopicId() == castOther.getTopicId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getExpertId();
		result = 37 * result + this.getTopicId();
		return result;
	}

}
