package com.dag.robot.entities;

// Generated 2015-5-13 19:55:40 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelPaperJournal generated by hbm2java
 */
@Entity
@Table(name = "rel_paper_journal", catalog = "db_expert_robot")
public class RelPaperJournal implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private RelPaperJournalId id;
	private Journal journal;
	private Paper paper;
	private String issue;

	public RelPaperJournal() {
	}

	public RelPaperJournal(RelPaperJournalId id, Journal journal, Paper paper,
			String issue) {
		this.id = id;
		this.journal = journal;
		this.paper = paper;
		this.issue = issue;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "paperId", column = @Column(name = "paperId", nullable = false)),
			@AttributeOverride(name = "jourId", column = @Column(name = "jourId", nullable = false)) })
	public RelPaperJournalId getId() {
		return this.id;
	}

	public void setId(RelPaperJournalId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jourId", nullable = false, insertable = false, updatable = false)
	public Journal getJournal() {
		return this.journal;
	}

	public void setJournal(Journal journal) {
		this.journal = journal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "paperId", nullable = false, insertable = false, updatable = false)
	public Paper getPaper() {
		return this.paper;
	}

	public void setPaper(Paper paper) {
		this.paper = paper;
	}

	@Column(name = "issue", nullable = false, length = 50)
	public String getIssue() {
		return this.issue;
	}

	public void setIssue(String issue) {
		this.issue = issue;
	}

}
